### PR TITLE
updated and cleaned up for Godot 4.2

### PR DESCRIPTION
**Pull request by victorbstan**
Figured I'd update this for 4.2 compat.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Cool, thanks for spending time on this. The root folder needs an appropriate `.gitignore` file, the `.godot` folder should not be part of the PR. Other than that, looks good

**Comment by victorbstan** [comment]
Updated the `.gitignore` file that was already there, and untracked `.godot` dir.

**Comment by victorbstan** [comment]
~~Looking at your original screenshot and at the new screenshot. It seems that the horizontal cameras are rendering upside-down...~~ Please check shader code, I had to make changes to get the projection to align right.

**Review by BastiaanOlij — APPROVED** [review]
Works for me, I only had an issue that it didn't import the sky texture the first time around but I think that is a Godot issue, not due to this project.

You did use your own master branch, that won't be an issue merging this but you'll have to rename your master branch to something else, and then repull master after this is merged.

**Comment by victorbstan** [comment]
Good point, I wasn't sure originally that I was going to do a PR.

**Comment by BastiaanOlij** [comment]
@victorbstan could you check one more thing for me, and that is why the main.tscn has grown to several megabytes? It looks like some of the assets have ended up inside of the scene instead of being loaded from source files.

**Comment by victorbstan** [comment]
I was testing out baked GI, and somehow some of the data became part of the Main scene? Had to manually delete it.

**Comment by BastiaanOlij** [comment]
Hah! Yeah that'll do it :)

**Comment by BastiaanOlij** [comment]
Thanks for the work! Cool to see this is finding some use in the world :)

**Pull request merged**
